
GET http://127.0.0.1:8000/bands?genre=Hip-Hop

###

GET http://127.0.0.1:8000/bands


###

GET http://127.0.0.1:8000/bands/1

###

GET http://127.0.0.1:8000/bands?q=Slow

###

GET http://127.0.0.1:8000/bands?has_albums=True


###

POST http://127.0.0.1:8000/bands
Content-Type: application/json

{
    "name": "Lucas",
    "genre": "hip-hop"
}

###

POST http://127.0.0.1:8000/bands
Content-Type: application/json

{
    "name": "Boards of Canada",
    "genre": "Rock",
    "albums": [
      {
        "title": "Tomorrow's Harvest",
        "release_date": "2013-01-01"
      },
      {
        "title": "Music Has The Right To Children",
        "release_date": "1998-01-01"
      }
    ]
}

###

GET http://127.0.0.1:8000/items/25?q=juanmi